### ISSUE TITLE
main.py closes after running 

### ISSUE THREAD

**Issue by mountaincastle47** [FusionSid/Reddit2Insta-Meme-Uploader#1]
immediately closes after running

**Comment by FusionSid** [comment]
Do you get any error messages?

**Comment by FusionSid** [comment]
Btw if youre using version one from the releases tab, thats old and buggy and I forgot to update it. Try cloning or downloading as zip and running the latest version

**Comment by mountaincastle47** [comment]
> Btw if youre using version one from the releases tab, thats old and buggy and I forgot to update it. Try cloning or downloading as zip and running the latest version

Oh okay i will try that and let you know thanks

**Comment by mountaincastle47** [comment]
> Btw if youre using version one from the releases tab, thats old and buggy and I forgot to update it. Try cloning or downloading as zip and running the latest version

ModuleNotFoundError: No module named 'discord' this shows up in termux :(

**Comment by mountaincastle47** [comment]
> Btw if youre using version one from the releases tab, thats old and buggy and I forgot to update it. Try cloning or downloading as zip and running the latest version

somehow fixed it in pycharm but now stuck on this 
PS E:\downloads\Compressed\Reddit2Insta-Meme-Uploader-2\Reddit2Insta-Meme-Uploader-2> python main.py
Traceback (most recent call last):
  File "E:\downloads\Compressed\Reddit2Insta-Meme-Uploader-2\Reddit2Insta-Meme-Uploader-2\main.py", line 10, in <module>
    from sidspackage import ColorPrint
  File "E:\downloads\Compressed\Reddit2Insta-Meme-Uploader-2\Reddit2Insta-Meme-Uploader-2\venv\lib\site-packages\sidspackage\__init__.py", line 1, in <module>
    from .paginator import Paginator
  File "E:\downloads\Compressed\Reddit2Insta-Meme-Uploader-2\Reddit2Insta-Meme-Uploader-2\venv\lib\site-packages\sidspackage\paginator.py", line 2, in <module>
    from discord_ui import View
ImportError: cannot import name 'View' from 'discord_ui' (E:\downloads\Compressed\Reddit2Insta-Meme-Uploader-2\Reddit2Insta-Meme-Uploader-2\venv\lib\site-packages\discord_ui\__init__.py)

**Comment by FusionSid** [comment]
@mountaincastle47
Oh I see its cause of sidspackage imports a paginator for discord.
I commented out all the lines that use that package.

**Comment by FusionSid** [comment]
if that didnt fix it
delete all the lines which are commented out or say `cp.print()`

**Comment by mountaincastle47** [comment]
> if that didnt fix it delete all the lines which are commented out or say `cp.print()`

now i think it works perfectly fine except you gotta manually fix folder loaction\Reddit2Insta-Meme-Uploader-main\Reddit2Insta-Meme-Uploader-main\venv\Lib\site-packages\sidspackage\paginator.py to

import discord
from discord_ui import View

class Paginator(View):
    def __init__(self, ctx, ems):
        super().__init__(timeout=10)
        self.ctx = ctx
        self.em = ems
        self.index = 0
    
    def add(self, embed):
        self.em.append(embed)
    
    @discord_ui.button(style=discord.ButtonStyle.green, emoji="⬅", custom_id="left")
    async def left(self, button, interaction):
        if self.index == 0:
            button = [x for x in self.children if x.custom_id=="left"][0]
            button.disabled = True
        else:
            button = [x for x in self.children if x.custom_id=="right"][0]
            button.disabled = False
            self.index -= 1
        em = self.em[self.index]
        await interaction.response.edit_message(view=self,embed=em)
    
    @discord_ui.button(style=discord.ButtonStyle.green, emoji="➡️", custom_id="right")
    async def right(self, button, interaction):
        if self.index == (len(self.em)-1):
            button = [x for x in self.children if x.custom_id=="right"][0]
            button.disabled = True
        else:
            button = [x for x in self.children if x.custom_id=="left"][0]
            button.disabled = False
            self.index += 1
        em = self.em[self.index]
        await interaction.response.edit_message(view=self,embed=em)

**Comment by mountaincastle47** [comment]
> if that didnt fix it delete all the lines which are commented out or say `cp.print()`

i only changed discord.ui to discord_ui

**Comment by FusionSid** [comment]
ok, Its probably cause im using pycord which is discord.ui which is why I don't get these errors lol
anyways if its fixed now should I close this issue?

**Comment by mountaincastle47** [comment]
btw anyway to configure which subreddit the bot scrapes?

**Comment by FusionSid** [comment]
yep

**Comment by mountaincastle47** [comment]
how may i ask?

**Comment by FusionSid** [comment]
on line 128 theres a list called `rpsnlist`
Just add extra subreddits to it

**Comment by mountaincastle47** [comment]
so you add like 'all' or 'subreddit name' ?

**Comment by FusionSid** [comment]
you add a subreddit name
Like right now its `rpsnlist = ['memes', 'dankmemes']`
if for example you want to scrape `r/funny`
you would add "funny" to the list
`rpsnlist = ['memes', 'dankmemes', 'funny']`

**Comment by mountaincastle47** [comment]
> you add a subreddit name Like right now its `rpsnlist = ['memes', 'dankmemes']` if for example you want to scrape `r/funny` you would add "funny" to the list `rpsnlist = ['memes', 'dankmemes', 'funny']`

alirght man thanks a lot for your time and effort. You are a life saver to my dying instagram account. Hope you have a wonderful day or night :)

**Comment by FusionSid** [comment]
no problem bro.
Also just letting you know don't run the bot to many times a day or you will get rate limited

**Comment by FusionSid** [comment]
you you have a good day/night too :)

**Comment by mountaincastle47** [comment]
> 

oh okay gotcha bro thanks a lot
