### ISSUE TITLE
Suggestion: make option to make the bot work (post) slower

### ISSUE THREAD

**Issue by mountaincastle47** [FusionSid/Reddit2Insta-Meme-Uploader#3]
In order to slick pass bot detection this will help i think

**Comment by FusionSid** [comment]
yea just change the time.sleep() to a higher time

**Comment by FusionSid** [comment]
on the line where it says
bot.upload_photo()
under that there is time.sleep(2)
just increase it to 20s or smth I guess

i'll make it adjustable in setup.py tomorrow
